function Test-PIMRuleChanged {
    <#
    .SYNOPSIS
        Compares a desired policy rule against the rule currently on the tenant.
    .DESCRIPTION
        Internal helper. Inspects only the fields present in the desired rule.
        Returns $true when at least one field differs (i.e. a PATCH is needed),
        or $false when every checked field already matches the current value.

        Comparison is rule-type aware:
          Expiration_*   - isExpirationRequired, maximumDuration
          Enablement_*   - enabledRules (order-insensitive)
          Notification_* - isDefaultRecipientsEnabled, notificationLevel,
                           notificationRecipients (order-insensitive)
          Approval_*     - isApprovalRequired, approvalMode, primaryApprover IDs
    .PARAMETER Desired
        The hashtable generated by ConvertTo-PIMPolicyRules.
    .PARAMETER Current
        The PSCustomObject rule returned by the Graph API (may be $null).
    .OUTPUTS
        [bool] — $true when the rule needs updating, $false when it is already current.
    #>
    [CmdletBinding()]
    [OutputType([bool])]
    param (
        [Parameter(Mandatory)]
        [hashtable]$Desired,

        [Parameter()]
        [PSCustomObject]$Current
    )

    # No current rule in the policy → always needs update
    if ($null -eq $Current) { return $true }

    $ruleId = $Desired['id']

    switch -Wildcard ($ruleId) {

        'Expiration_*' {
            if ($Desired.ContainsKey('isExpirationRequired') -and
                ($Desired['isExpirationRequired'] -ne $Current.isExpirationRequired)) { return $true }
            if ($Desired.ContainsKey('maximumDuration') -and
                ($Desired['maximumDuration'] -ne $Current.maximumDuration)) { return $true }
            return $false
        }

        'Enablement_*' {
            if ($Desired.ContainsKey('enabledRules')) {
                $desiredRules = @($Desired['enabledRules'] | Sort-Object)
                $currentRules = @($Current.enabledRules   | Sort-Object)
                if (Compare-Object $desiredRules $currentRules) { return $true }
            }
            return $false
        }

        'Notification_*' {
            if ($Desired.ContainsKey('notificationLevel') -and
                ($Desired['notificationLevel'] -ne $Current.notificationLevel)) { return $true }
            if ($Desired.ContainsKey('isDefaultRecipientsEnabled') -and
                ($Desired['isDefaultRecipientsEnabled'] -ne $Current.isDefaultRecipientsEnabled)) { return $true }
            if ($Desired.ContainsKey('notificationRecipients')) {
                $desiredRec = @($Desired['notificationRecipients'] | Sort-Object)
                $currentRec = @($Current.notificationRecipients   | Sort-Object)
                if (Compare-Object $desiredRec $currentRec) { return $true }
            }
            return $false
        }

        'Approval_*' {
            if (-not $Desired.ContainsKey('setting')) { return $false }
            $ds = $Desired['setting']
            $cs = $Current.setting
            if ($null -eq $cs) { return $true }

            if ($ds.ContainsKey('isApprovalRequired') -and
                ($ds['isApprovalRequired'] -ne $cs.isApprovalRequired)) { return $true }
            if ($ds.ContainsKey('approvalMode') -and
                ($ds['approvalMode'] -ne $cs.approvalMode)) { return $true }

            if ($ds.ContainsKey('approvalStages')) {
                $desiredStages = @($ds['approvalStages'])
                $currentStages = @($cs.approvalStages)

                if ($desiredStages.Count -ne $currentStages.Count) { return $true }

                for ($s = 0; $s -lt $desiredStages.Count; $s++) {
                    $desiredApprovers = @($desiredStages[$s]['primaryApprovers'])
                    $currentApprovers = @($currentStages[$s].primaryApprovers)

                    if ($desiredApprovers.Count -ne $currentApprovers.Count) { return $true }

                    $desiredIds = @($desiredApprovers | ForEach-Object { $_['userId'] ?? $_['groupId'] } | Sort-Object)
                    $currentIds = @($currentApprovers | ForEach-Object { $_.userId   ?? $_.groupId   } | Sort-Object)

                    if (Compare-Object $desiredIds $currentIds) { return $true }
                }
            }
            return $false
        }

        default {
            # Unknown rule type — always patch to be safe
            return $true
        }
    }
}
